AWSTemplateFormatVersion: '2010-09-09'

Parameters:
  BucketName:
    Type: String
    Description: S3 Bucket Name
    Default: AppSample

Resources:

  AppSampleS3Bucket:
    Type: AWS::CloudFormation::Stack
    Properties:
        TemplateURL: ../templates/S3/S3Bucket.yaml
        Parameters:
          BucketName: !Ref BucketName
    DeletionPolicy: Delete
    UpdateReplacePolicy: Delete



Outputs:
  AppSampleS3Bucket:
    Value: !GetAtt AppSampleS3Bucket.Outputs.BucketName
    Export:
      Name: !Sub "${AWS::StackName}-BucketName"
  AppSampleS3BucketArn:
    Value: !GetAtt AppSampleS3Bucket.Outputs.BucketArn
    Export:
      Name: !Sub "${AWS::StackName}-BucketArn"



