AWSTemplateFormatVersion: "2010-09-09"

Parameters:
  BucketName:
    Type: String
    Description: Name of the S3 Bucket.
    Default: aws-gitops-vanilla

Resources:
  S3Bucket:
    Type: "AWS::S3::Bucket"
    Properties:
      BucketName: !Ref BucketName
    Metadata:
      checkov:
        skip:
          - id: "CKV_AWS_284"
            comment: "Justificação para ignorar a verificação de replicação do bucket S3"

Outputs:
  S3BucketName:
    Value: !Ref BucketName
    Description: S3 Bucket Name
    Export:
      Name: !Sub "${AWS::StackName}-S3BucketName"
  S3BucketArn:
    Value: !GetAtt S3Bucket.Arn
    Description: S3 Bucket Arn
    Export:
      Name: !Sub "${AWS::StackName}-S3BucketArn"
