version: 0.2

env:
  git-credential-helper: yes
  shell: bash

phases:
  install:
    commands:
      - curl --proto '=https' --tlsv1.2 -sSf https://raw.githubusercontent.com/aws-cloudformation/cloudformation-guard/main/install-guard.sh | sh
      - export PATH=~/.guard/bin:$PATH
      - pip install report2junit
  pre_build:
    commands:
      - git config --global --add safe.directory /codebuild/output/srcDownload/src
      - source cloudformation/resources/shared/get_changed_files.sh --git-compare
  build:
    commands:
      - PATH=${PATH}:~/.guard/bin
      - bash cloudformation/resources/cfn-guard/guard-validate.sh --git-compare
  post_build:
    commands:
      - |
        TEMPLATE_ERROR_COUNT=$(cat ${TEMP_DIR}/validation_error_count.txt)
        VALIDATION_RESULT=$(cat ${TEMP_DIR}/validation_output.txt)

        aws codecommit post-comment-for-pull-request \
          --pull-request-id "${CI_PULL_REQUEST_ID}" \
          --repository-name "${CI_REPOSITORY_NAME}" \
          --before-commit-id "${CI_SOURCE_COMMIT}" \
          --after-commit-id "${CI_DESTINATION_COMMIT}" \
          --content "${VALIDATION_RESULT}"

        if [[ $TEMPLATE_ERROR_COUNT -gt 0 ]]; then

            aws codecommit update-pull-request-approval-state \
                --pull-request-id "${CI_PULL_REQUEST_ID}"  \
                --revision-id ${CI_REVISION_ID}  \
                --approval-state "REVOKE"

        fi
artifacts:
  base-directory: .GITOPS_TEMP/cloudformation/resources/cfn-guard/reports #TODO: .GITOPS_TEMP está hard-coded
  files:
    - '**/*'
  discard-paths: yes

reports:
  guard-reports:
    base-directory:  .GITOPS_TEMP/cloudformation/resources/cfn-guard/reports #TODO: .GITOPS_TEMP está hard-coded
    file-format: JUNITXML
    discard-paths: yes