version: 0.2

env:
  git-credential-helper: yes
  shell: bash

phases:
  install:
    commands:
      - curl --proto '=https' --tlsv1.2 -sSf https://raw.githubusercontent.com/aws-cloudformation/cloudformation-guard/main/install-guard.sh | sh
      - export PATH=~/.guard/bin:$PATH
      - pip install report2junit
  pre_build:
    commands:
      - git config --global --add safe.directory /codebuild/output/srcDownload/src
      - source cloudformation/resources/shared/get_changed_files.sh --git-compare
  build:
    commands:
      - PATH=${PATH}:~/.guard/bin
      - bash cloudformation/resources/cfn-guard/guard-validate.sh --git-compare
  post_build:
    commands:
      - |
        COMMENT_CONTENT="Pull request validation completed on `date`"
        TEMPLATE_ERROR_COUNT=$(cat ${TEMP_DIR}/validation_error_count.txt)

        if [[ $TEMPLATE_ERROR_COUNT -gt 0 ]]; then
          COMMENT_CONTENT="${COMMENT_CONTENT}\n\n**Template Validation Errors ** $TEMPLATE_ERROR_COUNT"
        fi

        VALIDATION_RESULT=$(cat ${TEMP_DIR}/validation_output.txt)
        COMMENT_CONTENT="${COMMENT_CONTENT}\n\n$VALIDATION_RESULT"

        aws codecommit post-comment-for-pull-request \
          --pull-request-id "${CI_PULL_REQUEST_ID}" \
          --repository-name "${CI_REPOSITORY_NAME}" \
          --before-commit-id "${CI_SOURCE_COMMIT}" \
          --after-commit-id "${CI_DESTINATION_COMMIT}" \
          --content "${COMMENT_CONTENT}"

        if [[ $TEMPLATE_ERROR_COUNT -gt 0 ]]; then

            aws codecommit update-pull-request-approval-state \
                --pull-request-id "${CI_PULL_REQUEST_ID}" \
                --repository-name "${CI_REPOSITORY_NAME}" \
                --approval-state REJECTED \
                --revision "${CI_DESTINATION_COMMIT}" \
                --override-status REJECTED

        fi
artifacts:
  base-directory: .GITOPS_TEMP/cloudformation/resources/cfn-guard/reports #TODO: .GITOPS_TEMP está hard-coded
  files:
    - '**/*'
  discard-paths: yes

reports:
  guard-reports:
    base-directory:  .GITOPS_TEMP/cloudformation/resources/cfn-guard/reports #TODO: .GITOPS_TEMP está hard-coded
    file-format: JUNITXML
    discard-paths: yes